import type { Metadata } from "next";
import "./shared/globals.css";
import { poppins } from "./shared/fonts";
import NavBar from "./components/nav-bar";

export const metadata: Metadata = {
  title: "Crud Users APP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        {/* /////////////////////////// */}
        <section className="master-container ">
          <NavBar />
          <section className="main-content">{children}</section>
        </section>
      </body>
    </html>
  );
}
